#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'beautifulDays' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER i
#  2. INTEGER j
#  3. INTEGER k
#
def reverseNum(n):
    s = list(str(n))
    s_rev = s[::-1]
    rev = int(''.join(s_rev))
    return rev

def beautifulDays(i, j, k):
    count_beautiful = 0
    for num in range(i,j+1):
        rev_num = reverseNum(num)
        if abs(rev_num - num) % k == 0:
            count_beautiful += 1
    return count_beautiful

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    i = int(first_multiple_input[0])

    j = int(first_multiple_input[1])

    k = int(first_multiple_input[2])

    result = beautifulDays(i, j, k)

    fptr.write(str(result) + '\n')

    fptr.close()
